// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNkLGv8mQ9Fv4aZL4jMUXineOuvUYdNUI',
    appId: '1:764590118599:web:08e152a61570a0841150e2',
    messagingSenderId: '764590118599',
    projectId: 'bloodbank-75383',
    authDomain: 'bloodbank-75383.firebaseapp.com',
    storageBucket: 'bloodbank-75383.firebasestorage.app',
    measurementId: 'G-9FY6TQ17G0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa-4wiqquDETD3gi117LKW2v2OJi5lkrk',
    appId: '1:764590118599:android:b6ce6ad12c5ec5c51150e2',
    messagingSenderId: '764590118599',
    projectId: 'bloodbank-75383',
    storageBucket: 'bloodbank-75383.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6FQdhcUh11FOhPff03X_OgsakeCEzYeo',
    appId: '1:764590118599:ios:0a62dd504c2e125d1150e2',
    messagingSenderId: '764590118599',
    projectId: 'bloodbank-75383',
    storageBucket: 'bloodbank-75383.firebasestorage.app',
    iosBundleId: 'com.example.bloodbank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6FQdhcUh11FOhPff03X_OgsakeCEzYeo',
    appId: '1:764590118599:ios:0a62dd504c2e125d1150e2',
    messagingSenderId: '764590118599',
    projectId: 'bloodbank-75383',
    storageBucket: 'bloodbank-75383.firebasestorage.app',
    iosBundleId: 'com.example.bloodbank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNkLGv8mQ9Fv4aZL4jMUXineOuvUYdNUI',
    appId: '1:764590118599:web:2d799caa873465621150e2',
    messagingSenderId: '764590118599',
    projectId: 'bloodbank-75383',
    authDomain: 'bloodbank-75383.firebaseapp.com',
    storageBucket: 'bloodbank-75383.firebasestorage.app',
    measurementId: 'G-C1P3Q8SV6W',
  );
}
